# Generated by Django 4.0.6 on 2022-07-22 10:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('clothingstore', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='placed_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
