# Generated by Django 4.0.5 on 2022-06-23 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clothingstore', '0002_address'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name_plural': 'addresses'},
        ),
    ]
